//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFLearn
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Client
    {
        public int Pid { get; set; }
        public string Code { get; set; }
        public string Client { get; set; }
        public Nullable<int> ClientChainXid { get; set; }
        public string LegalName { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<int> PriorityXid { get; set; }
        public Nullable<int> LanguageXid { get; set; }
        public int ParentXid { get; set; }
        public string ReceiveOtherInformation { get; set; }
        public string SubscribeToThirdParty { get; set; }
        public string Status { get; set; }
        public string ClientType { get; set; }
        public string ShowCommOnInv { get; set; }
        public string TaxRecoverableYN { get; set; }
        public string VatNumber { get; set; }
        public string VatRegistrationNo { get; set; }
        public string NominalCode { get; set; }
        public string PrepayReqd { get; set; }
        public Nullable<int> NationalityXid { get; set; }
        public Nullable<int> DefaultCurrencyXid { get; set; }
        public Nullable<int> InvoiceDays { get; set; }
        public Nullable<int> CreditDays { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<int> MarketXid { get; set; }
        public string wwwAddress { get; set; }
        public Nullable<int> SourceXid { get; set; }
        public string CommunicationMethod { get; set; }
        public string HeadOfficeYN { get; set; }
        public string CommissionYN { get; set; }
        public Nullable<int> NationXid { get; set; }
        public Nullable<int> TaxApplicableCountryXid { get; set; }
        public string PrivateYN { get; set; }
        public Nullable<int> SubStatusXid { get; set; }
        public Nullable<int> SubMarketXid { get; set; }
        public Nullable<int> DefaultTariffXid { get; set; }
        public Nullable<decimal> ForwardBookingsCreditLimit { get; set; }
        public Nullable<decimal> PastBookingsCreditLimit { get; set; }
        public string PastBookingsBasedOn { get; set; }
        public Nullable<int> OnlineBookingCutOffDays { get; set; }
        public Nullable<int> NotesXid { get; set; }
        public System.DateTime LastEdit { get; set; }
        public int LastEditByXid { get; set; }
        public int CompanyXid { get; set; }
        public string UseClientLogoYN { get; set; }
        public string AutoInvoicingYN { get; set; }
        public string AutoInvoiceLogic { get; set; }
        public string AutoInvoicePBPC { get; set; }
        public Nullable<int> IncreaseCancellationDays { get; set; }
        public string SameAsBuyCurrencyYN { get; set; }
        public string ShowMsbeYN { get; set; }
        public Nullable<int> DateFormat { get; set; }
        public string ExportedFileName { get; set; }
        public Nullable<int> DefaultExpiryDays { get; set; }
        public Nullable<int> B2BExpiryDays { get; set; }
        public Nullable<int> B2CExpiryDays { get; set; }
        public Nullable<int> reminderdays1 { get; set; }
        public Nullable<int> reminderdays2 { get; set; }
        public string SlabOrTariff { get; set; }
        public string SupplierBatchSenderAddress { get; set; }
        public string SupplierBatchSenderName { get; set; }
        public string ShowClientNameOnSupplierDocYN { get; set; }
        public string ShowAllocationLogicYN { get; set; }
        public string ScheduleDay { get; set; }
        public string BookingNotificationEmailAddress { get; set; }
        public Nullable<System.DateTime> ExtractDate { get; set; }
        public string ExtractYN { get; set; }
        public string ExportToAccounts { get; set; }
        public string AutoCancelYN { get; set; }
        public string AutoReminderYN { get; set; }
        public string ClientInSecureCreditYN { get; set; }
    }
}
