//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFLearn
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_DiscountType
    {
        public int Pid { get; set; }
        public string DiscountType { get; set; }
        public Nullable<int> NotesXid { get; set; }
        public System.DateTime LastEdit { get; set; }
        public int LastEditByXid { get; set; }
        public int CompanyXid { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Code { get; set; }

        public int YME { get; set; }

    }
}
